project:
  type: book

book:
  title: "R for Data Analytics"
  author: "Siju Swamy"
  date: "2/19/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - basics.qmd
    - data-cleaning.qmd
    - descriptive-statistics.qmd
    - EDA.qmd
    - visualization-vs-presentation.qmd
    - statistical-methods.qmd
    - micro-project.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



